server:
  port: ${APP_PORT:8082}
  servlet:
    context-path: /account-test

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      platform: postgres

config:
  clients:
    client:
      base-url: ${CONFLIG_CLIENT_BASE_URL}


