server:
  port: ${APP_PORT:8081}
  servlet:
    context-path: /client-test

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      platform: postgres


