version: '3.8'
services:
  account-service:
    build:
      context: .
      dockerfile: ./containers/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - ./environment/.env
    volumes:
      - .:/account-microservice
    networks:
      - devsu-test-red

networks:
  devsu-test-red:
    external: true